// Generated by gencpp from file custom_msgs/CropList.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CROPLIST_H
#define CUSTOM_MSGS_MESSAGE_CROPLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/Crop.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct CropList_
{
  typedef CropList_<ContainerAllocator> Type;

  CropList_()
    : size(0)
    , data()  {
    }
  CropList_(const ContainerAllocator& _alloc)
    : size(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _size_type;
  _size_type size;

   typedef std::vector< ::custom_msgs::Crop_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::custom_msgs::Crop_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::custom_msgs::CropList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::CropList_<ContainerAllocator> const> ConstPtr;

}; // struct CropList_

typedef ::custom_msgs::CropList_<std::allocator<void> > CropList;

typedef boost::shared_ptr< ::custom_msgs::CropList > CropListPtr;
typedef boost::shared_ptr< ::custom_msgs::CropList const> CropListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::CropList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::CropList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'custom_msgs': ['/home/fitocuan/essex_ws/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CropList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CropList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CropList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CropList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CropList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CropList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::CropList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d586f724d05e2e00f68131d048622687";
  }

  static const char* value(const ::custom_msgs::CropList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd586f724d05e2e00ULL;
  static const uint64_t static_value2 = 0xf68131d048622687ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::CropList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/CropList";
  }

  static const char* value(const ::custom_msgs::CropList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::CropList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 size\n\
Crop[] data\n\
================================================================================\n\
MSG: custom_msgs/Crop\n\
geometry_msgs/Point32 coor\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::custom_msgs::CropList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::CropList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CropList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::CropList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::CropList_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msgs::Crop_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CROPLIST_H
